service: serverless-ecommerce-api-notification-service
frameworkVersion: '3'
plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

functions: 
  subscribe: 
    handler: ./src/subscribe.main
    events:
      - http:
          path: /subscribe
          method: post

  publish: 
    handler: ./src/publish.main
    events:
      - http: 
          path: /publish
          method: post
          
  sendUserUpdatedEmail: 
    handler: ./src/sendUserUpdatedEmail.ts
    events: 
      - http:
          path: /send-update-email
          method: post

package:
  individually: false

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'aws-sdk'
    target: node14
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10
