service: serverless-ecommerce-api-categories-service
frameworkVersion: '3'
plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    TABLE_NAME: 'BASE'

functions: 
  getCategory: 
    handler: ./src/getCategory.main 
    events:
      - http: 
          path: /categories/{category}
          method: get
  createCategory: 
    handler: ./src/createCategory.main
    events:
      - http: 
          path: /categories/create
          method: post
  updateCategory: 
    handler: ./src/updateCategory.main
    events:
      - http: 
          path: /categories/{category}/update
          method: put
  getAllCategories: 
    handler: ./src/getAllCategories.main
    events:
      - http:
          path: /categories
          method: get
  
  deleteCategory: 
    handler: ./src/deleteCategory.main
    events:
      - http:
          path: /categories/{category}/delete
          method: delete
  getProducts: 
    handler: ./src/getProducts.main
    events:
      - http: 
          path: /categories/{category}/products
          method: get

package:
  individually: false

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'aws-sdk'
    target: node14
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10
