service: serverless-ecommerce-api-users-service
frameworkVersion: '3'
plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    TABLE_NAME: 'BASE'
    USER_PK: 'USER'

functions: 
  getUser: 
    handler: ./src/getUser.main 
    events:
      - http: 
          path: /users/{username}
          method: get
  createUser: 
    handler: ./src/createUser.main
    events:
      - http: 
          path: /users/create
          method: post
  updateUser: 
    handler: ./src/updateUser.main
    events:
      - http: 
          path: /users/{username}/update
          method: put
  getAllUsers: 
    handler: ./src/getAllUsers.main
    events:
      - http:
          path: /users
          method: get
  
  deleteUser: 
    handler: ./src/deleteUser.main
    events:
      - http:
          path: /users/{username}/delete
          method: delete
package:
  individually: false

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'aws-sdk'
    target: node14
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10
