service: serverless-ecommerce-api-products-service
frameworkVersion: '3'
plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    TABLE_NAME: 'BASE'

functions: 
  getProduct: 
    handler: ./src/getProduct.main 
    events:
      - http: 
          path: /products/{product}
          method: get
  createProduct: 
    handler: ./src/createProduct.main
    events:
      - http: 
          path: /products/create
          method: post
  updateProduct: 
    handler: ./src/updateProduct.main
    events:
      - http: 
          path: /products/{product}/update
          method: put
  getAllProducts: 
    handler: ./src/getAllProducts.main
    events:
      - http:
          path: /products
          method: get
  
  deleteProduct: 
    handler: ./src/deleteProduct.main
    events:
      - http:
          path: /products/{product}/delete
          method: delete
package:
  individually: false

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'aws-sdk'
    target: node14
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10
